### ISSUE TITLE
Error building react-lib in Stencil-toolkit-nx repo

### ISSUE THREAD

**Issue by bellindj** [aiao-io/aiao#52]
Thanks so much for creating the stencil-toolkit plugin for NX! I am running the stencil-toolkit-nx project under integrations and facing an issue building the react-lib.

Steps:
clone repo
`cd integration/stencil-toolkit-nx`
edit package.json, change `"@aiao/stencil-toolkit": "file:../../dist/libs/stencil-toolkit",` to `"@aiao/stencil-toolkit": "0.0.10",`
`yarn`
`ng build stencil-lib` - works fine
`ng build angular-lib` - works fine
`ng build react-lib' - gives the below error:

CINMAC12801:stencil-toolkit-nx dan$ ng build react-lib
Bundling...
{ Error: /Users/dan/aiao/integration/stencil-toolkit-nx/libs/react-lib/src/lib/react-component-lib/createOverlayComponent.tsx(15,17): semantic error TS2742: The inferred type of 'createOverlayComponent' cannot be named without a reference to 'react-dom/node_modules/@types/react'. This is likely not portable. A type annotation is necessary.
    at error (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup/dist/rollup.js:9419:30)
    at throwPluginError (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup/dist/rollup.js:15699:12)
    at Object.error (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup/dist/rollup.js:15754:24)
    at Object.error (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup/dist/rollup.js:16146:38)
    at RollupContext.error (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:17194:30)
    at lodash_3 (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24958:23)
    at arrayEach (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:534:11)
    at forEach (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:9360:14)
    at printDiagnostics (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:24931:5)
    at cache.getCompiled (/Users/dan/aiao/integration/stencil-toolkit-nx/node_modules/@nrwl/web/node_modules/rollup-plugin-typescript2/dist/rollup-plugin-typescript2.cjs.js:27356:21)
  id:
   '/Users/dan/aiao/integration/stencil-toolkit-nx/libs/react-lib/src/lib/react-component-lib/createOverlayComponent.tsx',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'rpt2' }
'@stencil-toolkit-nx/stencil-lib/loader' is imported by libs/react-lib/src/lib/proxies.ts, but could not be resolved – treating it as an external dependency
'@stencil-toolkit-nx/stencil-lib/loader' is imported by libs/react-lib/src/lib/proxies.ts, but could not be resolved – treating it as an external dependency
'@stencil-toolkit-nx/stencil-lib/loader' is imported by libs/react-lib/src/lib/proxies.ts, but could not be resolved – treating it as an external dependency
No name was provided for external module '@stencil-toolkit-nx/stencil-lib/loader' in output.globals – guessing 'loader'

Is that project building for you?

**Comment by Jimmysh** [comment]
@bellindj 
need clean stencil output files. 
https://github.com/aiao-io/aiao/blob/master/integration/stencil-toolkit-nx/libs/stencil-lib/scripts/build-clean.js

You can use `yarn build:libs` build all libs.

**Comment by bellindj** [comment]
That worked, thanks so much for the instructions and your commit!

**Comment by Jimmysh** [comment]
@bellindj  FYI
https://github.com/nrwl/nx/issues/2496
I make a hotfix to fix it.
https://github.com/aiao-io/aiao/tree/master/tools/hotfix

**Comment by bellindj** [comment]
@Jimmysh great thanks for including me on this for visibility! I haven’t pulled the latest in a bit but will do that.
